version: "3.10"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: TRUE
      VERSION: LATEST
      MODE: creative
      LEVEL_TYPE: flat
      GENERATOR_SETTINGS: '{"lakes":false,"features":false,"layers":[{"block":"minecraft:air","height":1}],"structures":{"structures":{}}}'
      DIFFICULTY: peaceful
      GENERATE_STRUCTURES: false

      RCON_PASSWORD: jsx
